package it.univaq.technical;

public enum TipoAttesa {
    SCELTA_MOSSA_PRINCIPALE,
    SCELTA_CARTA_EROE,
    SCELTA_CARTA_OGGETTO,
    SCELTA_CARTA_MAGIA,
    CONFERMA_EFFETTO,
    SCELTA_MOSTRO_DA_ATTACCATARE,
    SCELTA_BERSAGLIO,
    RICHIESTA_TAVOLO
}
